# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "miltonkeynespm"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
template_toolkit: TT

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'


techmeet:
    Date: 16/06/2015
    Time: 7pm
    Address: IMS Evolve, 2nd Floor, Matrix House, 2 North Forth Street, Central Milton Keynes, MK9 1NJ
    Map: https://goo.gl/maps/F49T1
    Talks:
        Rick Deller: The Perl recruitment Market
        Paul Mooney: PAAS Heroku with Perl
        Colin Newell: Jenkins build indicator on a Raspberry Pi and quick perl script
        Colin Bradford: Websockets and Mojolicious for real time applications
		Nick Morrott: Writing a Vim syntax checker
		Nick Morrott: Plugins that overload vim functionality without overloading your brain
